### ISSUE TITLE
CPU Max Speed

### ISSUE THREAD

**Issue by sezginyildirim91** [jcomeauictx/slotmachine#1]
I have a 4.10 Ghz processor. When I run the software it is using 30% CPU. What should I do to run this at maximum speed. Thanks.

**Comment by jcomeauictx** [comment]
I can't duplicate this, not having a fast computer. It runs 100% CPU on mine. I'll leave the issue open in case anyone else has some ideas.

**Comment by divinity76** [comment]
maybe you're IO-capped?

**Comment by jcomeauictx** [comment]
@divinity76 is probably right. I was able to IO-cap mine by running two instances, one for each CPU: `python3 ./slotmachine.py | python3 ./slotmachine.py`. So I messed with the code a bit, and made it so enabling optimization (`python3 -OO slotmachine.py` or simply `./slotmachine.py`) will *not* output each guess. It should run close to 100% CPU now, let me know.

**Comment by jcomeauictx** [comment]
Going to assume fixed and close this. Reopen if necessary.

**Comment by divinity76** [comment]
could also be a multi-core OS thing. On Linux, if you have 3 cores (and yes that exist, eg "AMD Phenom II X3 B77", it's basically a 4-core CPU with a broken core disabled, AMD opted to disable a broken core instead of throwing it away because 3/4 cores worked fine.), and you max out 1 core (and only 1 core): 

Windows will say: You're using 100/3=33% cpu (because you have 3 cores and you're maxing out 1 of them)
Linux will say: you're using 100% cpu (because you're maxing out 1 of them)

by contrast, if you have 3 cores and your program is maxing out all of them, 
Windows will say: you're using 100% cpu.
Linux will say: you're using 300% cpu.
